#  sudo docker run --name mysqlDB -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=Ecommerce_users -p 3306:3306 mysql:5.7
#    --> docker run --name temp --rm -p 8080:8080 --network PCD_network  application:latest
#
#
#


version: "3"

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=Ecommerce_users
    ports:
      - "3306:3306"
    volumes:
      - ./Ecommerce_users.sql:/docker-entrypoint-initdb.d/Ecommerce_users.sql
    networks:
      springboot-mysql-net:


  app:
    depends_on:
      - mysqldb
    build:
      context: ./mysqlshit
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env.docker
    ports:
      - "8080:8080"
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/Ecommerce_users
      - spring.datasource.username=root
      - spring.datasource.password=1234
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:

  react_l:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - app
    networks:
      springboot-mysql-net:


networks:
  springboot-mysql-net:
