version: "3"

services:
    react_l:
        build:
          context: ./Frontend_V2.0
        ports:
          - "3000:3000"
        environment:
          - NODE_ENV=development
        networks:
          - drawini-net
    postgres:
        image: postgres:latest
        container_name: postgres_db
        environment:
          POSTGRES_DB: pcd
          POSTGRES_USER: khaled
          POSTGRES_PASSWORD: 1234
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        networks:
          - drawini-net

    web:
        image: nginx
        volumes:
         - ./templates:/etc/nginx/templates
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
         - "8080:8080"
        extra_hosts:
         - "host.docker.internal:host-gateway"

    java:
       build:
         context: ./SpringBackend_V2.0/
       depends_on:
         - postgres
       environment:
         - SPRING_DATASOURCE_URL=jdbc:postgresql://4.180.6.234:5432/pcd
         - SPRING_DATASOURCE_USERNAME=khaled
         - SPRING_DATASOURCE_PASSWORD=1234
         - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
         - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
         - SPRING_JPA_SHOW_SQL=true
         - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
         - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
         - SPRING_MAIL_HOST=smtp.gmail.com
         - SPRING_MAIL_PORT=587
         - SPRING_MAIL_USERNAME=khaled.mrad@ensi-uma.tn
         - SPRING_MAIL_PASSWORD=pywh domh rlsd vezm
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=*
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTION_TIMEOUT=5000
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT=3000
         - SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITE_TIMEOUT=5000

       ports:
         - "8081:8081"
       extra_hosts:
         - "host.docker.internal:host-gateway"


volumes:
    postgres_data:
networks:
    drawini-net:

