version: "3"

services:
    react_l:
        build:
          context: ./Frontend_V2.0
        ports:
          - "3000:3000"
        environment:
          - NODE_ENV=development
        networks:
          - drawini-net

networks:
    drawini-net:

