apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: drawini
  labels:
    app: postgresdeployment
    tier: database
spec:
  selector: # mysql Pod Should contain same labels
    matchLabels:
      app: postgresdeployment
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: postgresdeployment
        tier: database
    spec:
      containers:
      - image: postgres:latest # image from docker-hub
        name: postgres
        env:
        - name: POSTGRES_DB
          value: pcd
        - name: POSTGRES_USER # Setting Database Name from a 'ConfigMap'
          value: khaled
        - name: POSTGRES_PASSWORD
          value: "1234"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-vol
      volumes:
      - name: postgres-vol
        persistentVolumeClaim:
          claimName: postgres-vol
