apiVersion: v1
kind: Pod
metadata:
  name: pvc-inspector
spec:
  containers:
  - image: busybox
    name: pvc-inspector
    command: ["tail"]
    args: ["-f", "/dev/null"]
    volumeMounts:
    - mountPath: "/mnt/tmp"
      name: postgrespv
  volumes:
  - name: postgrespv
    persistentVolumeClaim:
      claimName: postgrespvclaim
# kubectl exec -it pvc-inspector -- sh
