apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvclaim
  namespace: drawini
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
