apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: drawini
  labels:
    app: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresdeployment
  type: ClusterIP
