db_url: jdbc:postgresql://10.244.0.214:5432/pcd

ingress-nginx:
  repository: "https://kubernetes.github.io/ingress-nginx"
  chart: "ingress-nginx"
  version: "4.0.6" # Adjust based on the chart's version you'd like to use
  namespace: "ingress-nginx"
  createNamespace: true
  releaseName: "ingress-nginx"

kubernetes_dashboard:
  namespace: kubernetes-dashboard
  create_namespace: true
  repo_url: "https://kubernetes.github.io/dashboard/"
  chart_name: kubernetes-dashboard/kubernetes-dashboard
