apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresconfigmap
  namespace: drawini
  labels:
    app: postgresstatefulset
data:
  POSTGRES_USER: "khaled"
  POSTGRES_PASSWORD: "1234"
  POSTGRES_DB: "pcd"
  PGDATA: "/var/lib/postgresql/data/pgdata" # Add this line
