apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: drawini
spec:
  selector:
    app: postgresstatefulset
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
  clusterIP: 10.0.212.207
