server:
  port: 8081

redis:
  host: "localhost"
  port : "6379"
  pass: ""
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    database: ${SPRING_JPA_DATABASE}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            trust: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
          connectiontimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTION_TIMEOUT}
          timeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT}
          writetimeout: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITE_TIMEOUT}
