# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: drawini
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: drawini.back.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: springbackend-service
            port:
              number: 8080
