apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
  namespace: drawini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot-backend
        image: khaledmraad/backpain
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: { ? { .Value.db_url } }
          # value: "jdbc:postgresql://10.244.0.214:5432/pcd"
